// flow-typed signature: 7444e73bf0aaae142a77ae386b0e177d
// flow-typed version: <<STUB>>/babel-plugin-styled-name_v2.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-styled-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-styled-name' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-styled-name/lib/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'babel-plugin-styled-name/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-styled-name/lib/index'>
}
